apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector

metadata:
  name: gateway
  namespace: observability

spec:

  mode: deployment
  replicas: 2

  image: otel/opentelemetry-collector-contrib:latest

  config:

    receivers:

      otlp:
        protocols:

          grpc:
            endpoint: 0.0.0.0:4317

          http:
            endpoint: 0.0.0.0:4318

    processors:

      attributes:

        actions:

          - key: customer.email
            action: upsert
            value: REDACTED

          - key: credit_card
            action: upsert
            value: MASKED

          - key: password
            action: delete

      batch: {}

    connectors:

      routing:

        default_pipelines:
          - traces/payment

        table:

          - context: resource
            condition: 'attributes["service.name"] == "payment-service"'
            pipelines:
              - traces/payment

          - context: resource
            condition: 'attributes["service.name"] == "user-service"'
            pipelines:
              - traces/user

          - context: resource
            condition: 'attributes["service.name"] == "order-service"'
            pipelines:
              - traces/order

          - context: resource
            condition: 'attributes["service.name"] == "inventory-service"'
            pipelines:
              - traces/inventory

          - context: resource
            condition: 'attributes["service.name"] == "notification-service"'
            pipelines:
              - traces/notification

          - context: resource
            condition: 'attributes["service.name"] == "checkout-service"'
            pipelines:
              - traces/checkout

    extensions:

      basicauth/payment:
        client_auth:
          username: admin
          password: Obs3rv@bility!2026

      basicauth/user:
        client_auth:
          username: admin
          password: Obs3rv@bility!2026

      basicauth/order:
        client_auth:
          username: admin
          password: Obs3rv@bility!2026

      basicauth/inventory:
        client_auth:
          username: admin
          password: Obs3rv@bility!2026

      basicauth/notification:
        client_auth:
          username: admin
          password: Obs3rv@bility!2026

      basicauth/checkout:
        client_auth:
          username: admin
          password: Obs3rv@bility!2026

    exporters:

      opensearch/payment:

        http:
          endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200

          tls:
            insecure_skip_verify: true

          auth:
            authenticator: basicauth/payment

        logs_index: traces-payment

      opensearch/user:

        http:
          endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200

          tls:
            insecure_skip_verify: true

          auth:
            authenticator: basicauth/user

        logs_index: traces-user

      opensearch/order:

        http:
          endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200

          tls:
            insecure_skip_verify: true

          auth:
            authenticator: basicauth/order

        logs_index: traces-order

      opensearch/inventory:

        http:
          endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200

          tls:
            insecure_skip_verify: true

          auth:
            authenticator: basicauth/inventory

        logs_index: traces-inventory

      opensearch/notification:

        http:
          endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200

          tls:
            insecure_skip_verify: true

          auth:
            authenticator: basicauth/notification

        logs_index: traces-notification

      opensearch/checkout:

        http:
          endpoint: https://opensearch-cluster-master.opensearch.svc.cluster.local:9200

          tls:
            insecure_skip_verify: true

          auth:
            authenticator: basicauth/checkout

        logs_index: traces-checkout

    service:

      extensions:
        - basicauth/payment
        - basicauth/user
        - basicauth/order
        - basicauth/inventory
        - basicauth/notification
        - basicauth/checkout

      pipelines:

        traces:

          receivers:
            - otlp

          processors:
            - attributes
            - batch

          exporters:
            - routing

        traces/payment:

          receivers:
            - routing

          exporters:
            - opensearch/payment

        traces/user:

          receivers:
            - routing

          exporters:
            - opensearch/user

        traces/order:

          receivers:
            - routing

          exporters:
            - opensearch/order

        traces/inventory:

          receivers:
            - routing

          exporters:
            - opensearch/inventory

        traces/notification:

          receivers:
            - routing

          exporters:
            - opensearch/notification

        traces/checkout:

          receivers:
            - routing

          exporters:
            - opensearch/checkout