apiVersion: apps/v1
kind: Deployment

metadata:
  name: telemetrygen
  namespace: apps

spec:
  replicas: 1

  selector:
    matchLabels:
      app: telemetrygen

  template:
    metadata:
      labels:
        app: telemetrygen

    spec:
      containers:

      - name: telemetrygen

        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest

        args:
          - traces
          - --otlp-endpoint=gateway-collector.observability.svc.cluster.local:4317
          - --otlp-insecure
          - --duration=inf
          - --rate=5
          - --service=payment-service
          - --telemetry-attributes=customer.email="jeet@example.com"
          - --telemetry-attributes=credit_card="4111111111111111"
          - --telemetry-attributes=password="supersecret"
          - --telemetry-attributes=cloud.region="us-east-1"
